### ISSUE TITLE
Cannot POST /api/v1/users/register 

### ISSUE THREAD

**Issue by paul-abhirup** [hiteshchoudhary/chai-backend#101]
i dont know what is wrong
console is showing mongoDB is been connected server is runnning at port 8000
Yet cant make post request in postman

```javascript
//app.js

import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";

const app = express();

// cross orign resource pairing 
app.use(cors({
  orgin: process.env.CORS_ORIGIN,
  credentials: true
})) 
app.use(express.json({limit: "16kb"}))
app.use(express.urlencoded({
  extended: true,
  limit: "16kb"
}))
app.use(express.static("public"))
app.use(cookieParser())

//routes import 
import userRouter from "./routes/user.routes.js"

//routes declaration
app.use("/api/v1/users", userRouter)
// // https://localhost:3000/api/v1/users/register

export { app }


```
```javascript
//user.controller.js

import { asyncHandler } from "../utils/asyncHandler.js";

const registerUser = asyncHandler( async (req,res) => {
  return res.status(200).json({
    message: "ok"
  })
})

export { registerUser }


```
```javascript
//asyncHandler.js

// using promise method 
const asyncHandler = () => {
  (req,res,next) => {
    Promise.resolve(requestHandler(req,res,next)).catch((err) => next(err))
  }
}

// learn about node.js api errors

export {asyncHandler}
```
```javascript
//user.routes.js

import { Router } from "express";
import { registerUser } from "../controllers/user.controller.js";

const router = Router();

// Add middleware to parse the request body
// router.use(express.json());

router.route("/register").post(registerUser); 

export default router;
```
```javascript


```

**Comment by msaad53407** [comment]
Have you imported the app in the index file. I was also having a similar problem and turn out that I had not imported my app file in index file. So give it a shot If you hadn't already

**Comment by vikramhamal** [comment]
//app.js

import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";

const app = express();

// cross orign resource pairing 
app.use(cors({
  orgin: process.env.CORS_ORIGIN,
  credentials: true
})) 
app.use(express.json({limit: "16kb"}))
app.use(express.urlencoded({
  extended: true,
  limit: "16kb"
}))
app.use(express.static("public"))
app.use(cookieParser())

//routes import 
import userRouter from "./routes/user.routes.js"

//routes declaration
app.use("/api/v1/users", userRouter)
// // https://localhost:3000/api/v1/users/register

export { app }

There is some mistake in your code . Please  check origin spelling in your code .

**Comment by vikramhamal** [comment]
Check 
app.use(cors({
orgin: process.env.CORS_ORIGIN,
credentials: true
}))  origin spelling mistake

**Comment by paul-abhirup** [comment]
> Check app.use(cors({ orgin: process.env.CORS_ORIGIN, credentials: true })) origin spelling mistake

yup fixed it but still same issue

**Comment by paul-abhirup** [comment]
> Have you imported the app in the index file. I was also having a similar problem and turn out that I had not imported my app file in index file. So give it a shot If you hadn't already

tried it 
```js
import {app} from "./app.js"
```
instead of const app = express()
but it is giving error like 
 Route.post() requires a callback function but got a [object Undefined]

**Comment by paul-abhirup** [comment]
> Have you imported the app in the index file. I was also having a similar problem and turn out that I had not imported my app file in index file. So give it a shot If you hadn't already

i am also thinking that my code is having issue with this app.js file

**Comment by paul-abhirup** [comment]
thank You everyone 
I had some issue in the asyncHandler.js file . There i forgot to take requestHandler as argument to function
```js
const asyncHandler = (requestHandler) => {
  return (req,res,next) => {
    Promise.resolve(requestHandler(req,res,next)).catch((err) => next(err))
  }
}
```
so when i was importing app.js it  was showing error as Route.post() blah blah 
I learned as the codebase in this app is very distributed so its important to check every interconnecting file structure.
