### ISSUE TITLE
Refresh token and Access token is not working

### ISSUE THREAD

**Issue by Steath094** [hiteshchoudhary/chai-backend#112]
![Screenshot (31)](https://github.com/hiteshchoudhary/chai-backend/assets/129878756/ba75f0d0-d231-44fc-bf3e-0db77e77cb6e)
![Screenshot (32)](https://github.com/hiteshchoudhary/chai-backend/assets/129878756/a53b753b-7746-4973-86b5-2c7264a55e1c)

generateAccessAndRefreshTokens Function is not working
Need Help!!!

**Comment by Krrishsahu06** [comment]
Hey! I'm having the same error can you tell me if you solved it or not
