### ISSUE TITLE
coverImage undefined issue

### ISSUE THREAD

**Issue by Krrishsahu06** [hiteshchoudhary/chai-backend#120]
I'm getting the " Cannot read properties of undefined (reading &#39;0&#39;)<br> &nbsp; &nbsp;at file:///C:/Users/krish/OneDrive/Desktop/Programming/Web%20development/Backend_project/src/controllers/user.controller.js:44:52<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</pre> ""
Its saying something is wrong with coverImage
![Screenshot 2024-05-07 235108](https://github.com/hiteshchoudhary/chai-backend/assets/133038939/d1c31c41-855c-405e-9118-c09b2532c5ee)
![Screenshot 2024-05-07 235227](https://github.com/hiteshchoudhary/chai-backend/assets/133038939/f5a45f21-3696-443e-a81f-3c1a7dcba42a)

**Comment by Krrishsahu06** [comment]
Now this undefined issue is solved but coverImage is not uploading. Cloudinary file giving error that "Did not find the file URL or path"

**Comment by ChandanPolai** [comment]
hey send me your profile my coverimage will be upload and delete successfully

**Comment by Krrishsahu06** [comment]
you can check my code in my BACKEND_PROJECT reprository

**Comment by ChandanPolai** [comment]
Ok

**Comment by Krrishsahu06** [comment]
did u see it @ChandanPolai

**Comment by ChandanPolai** [comment]
Hey you can use postman to register user so please send me the screenshot of your postman registration ok
