### ISSUE TITLE
Error in connecting to DB after creating my first route.

### ISSUE THREAD

**Issue by Harshitk816** [hiteshchoudhary/chai-backend#122]
So I am in the video of 'ROUTES AND CONTROLLER WITH DEBUGGING". After the creating my register route, i started the server and got:
`Server is running on port 8000
/n Database connected !! DB HOST: ac-fdtffkb-shard-00-02.gcq7rur.mongodb.net
Error in DB Connection TypeError: Cannot read properties of undefined (reading 'method')
    at Function.handle (C:\Users\Harshit\Desktop\Chai Aur Code Backend\chai_aur_backend\node_modules\express\lib\router\index.js:139:34)     
    at Function.handle (C:\Users\Harshit\Desktop\Chai Aur Code Backend\chai_aur_backend\node_modules\express\lib\application.js:181:10)      
    at app (C:\Users\Harshit\Desktop\Chai Aur Code Backend\chai_aur_backend\node_modules\express\lib\express.js:39:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/Harshit/Desktop/Chai%20Aur%20Code%20Backend/chai_aur_backend/src/index.js:15:1

`

I am unable to identify the problem yet. But it was connecting properly the last time I checked..
 This is my index.js
![image](https://github.com/hiteshchoudhary/chai-backend/assets/89690620/e63ed39d-7f8a-4dbd-9d06-5bdccf612149)

this is my db/index.js
![image](https://github.com/hiteshchoudhary/chai-backend/assets/89690620/7448472a-e3d9-4c42-af60-fe19b7402f83)

**Comment by shekharsikku** [comment]
Error in DB Connection TypeError: Cannot read properties of undefined (reading 'method') cannot find this error issue in this code. message me i will send you better code format

**Comment by mo14337** [comment]
There might be some issue with your USER schema

**Comment by Nishantsingh11** [comment]
-Hi harshit i think you have created the method some where but its empty as of now can you please check the code

**Comment by s0urav-hald3r** [comment]
While configuring the env file you write the path wrong.
It should be path: './.env'

**Comment by Harshitk816** [comment]
it was a simple fix i forgot to add a callback brackets to the error listening in the index.js:

`connectDB()
.then(()=>{
    app.on("error",(error)=>{
        console.log("Error in Database Connection : " + error);
    })
}`
previously it was : 
`connectDB()
.then(
    app.on("error",(error)=>{
        console.log("Error in Database Connection : " + error);
    )
}`
