### ISSUE TITLE
getting Error in login route while testing

### ISSUE THREAD

**Issue by ganeswar07** [hiteshchoudhary/chai-backend#24]
When i tested login route , i get some error and then i  debugged it . i noticed that data i received from req .body is a empty object.
where  should be problem ?

**Comment by SujalDhiman** [comment]
have you checked whether middleware express.json() is configured properly?

**Comment by aashishgulshan** [comment]
Actually I was getting the same issues when i send data through "Form-data"
![image](https://github.com/hiteshchoudhary/chai-backend/assets/78717816/78b15a71-ce67-4466-a1c6-88d8b4c51e99)

Try to send data from  Json

![image](https://github.com/hiteshchoudhary/chai-backend/assets/78717816/4f6ebb7c-837d-4aec-be48-4d8b263e79c0)

**Comment by AdityaBVerma** [comment]
I was having the same issue can you explain the reason for this behaviour to me

**Comment by aashishgulshan** [comment]
Hello @AdityaBVerma ,
Try to send data using "raw json". Which I mension in my screenshot.

Or please use full stable version of postman.
You might be get issue in vs code plugin.

**Comment by AdityaBVerma** [comment]
@aashishgulshan  
issue was resolved but I was just curious to know the reason for this behaviour of postman
but still thank you for replying
