### ISSUE TITLE
Error uploading Cover Image

### ISSUE THREAD

**Issue by TechWhiz03** [hiteshchoudhary/chai-backend#38]
**Cover Image not being saved to "Local Path" and therefore not on "Cloudinary" also even after providing it on postman
below are the attachments of output and my code  please help**
I have read all the previous solutions to similar issue but error dosen't resolve 

![Screenshot 2023-12-25 184823](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/c7e5c975-e92a-4539-a849-6bd1002c83e4)

**user.controller.js**

![Screenshot 2023-12-25 185242](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/28ac14a8-0e1d-4d1b-98ce-0795f035030c)

**cloudinary.js**

![Screenshot 2023-12-25 185416](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/76fd9839-06a8-427d-962a-2c7409d985d7)

**multer.middleware.js**

![Screenshot 2023-12-25 185549](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/ea1d34a2-d22c-4c4b-82c7-5f0787ef55f1)

**Comment by TechWhiz03** [comment]
@nirajchaurasiya

**Comment by ganeswar07** [comment]
Share your route file

**Comment by TechWhiz03** [comment]
![Screenshot 2023-12-25 192000](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/04ff6f1f-1f0d-4367-9a0e-902892888ad7)

**Comment by nirajchaurasiya** [comment]
Hey, man!
I have many questions because there can be so many ways that the coverImage is not being uploaded.
Can you provide me the repo URL and screenshots of your .env variables?

**Comment by ganeswar07** [comment]
Put a console log of req.files  in starting of controller. And share screenshot of it .

**Comment by TechWhiz03** [comment]
can we have a gmeet if any of you are available?
@nirajchaurasiya @ganeswar07

**Comment by nirajchaurasiya** [comment]
Sorry, man,
I am not available because I am outside.

**Comment by TechWhiz03** [comment]
ok

**Comment by TechWhiz03** [comment]
earlier coverImage array was also coming but now only avatar array is coming:

![Screenshot 2023-12-25 193625](https://github.com/hiteshchoudhary/chai-backend/assets/139670768/3f3e1699-d61c-495c-8a7a-34c57edeb5cb)

**Comment by TechWhiz03** [comment]
@nirajchaurasiya pin me when you are available for gmeet

**Comment by TechWhiz03** [comment]
@ganeswar07  ss added

**Comment by nirajchaurasiya** [comment]
Yeah, that's okay, but can you share your repo and let us check if we can fix the issue?

**Comment by TechWhiz03** [comment]
@nirajchaurasiya  here is the link
https://github.com/TechWhiz03/StreamSpot

**Comment by nirajchaurasiya** [comment]
Hey, man.
After reviewing your code, I don't think there is an issue with anything.
Are you sure you are not getting the cover image on your server after sending it from Postman?

**Comment by TechWhiz03** [comment]
yes i also think that there is no error but somehow the coverImage is not saving to my local server 
i have also attached screenshot of response in my 1st comment
if we can have gmeet i think it will be appreciated

**Comment by ganeswar07** [comment]
I think the problem was in the Postman request. So, delete all key-value pairs and set them again. Type the key properly and don't make any typos.

**Comment by TechWhiz03** [comment]
I have done that many times then also I'm not getting cover image

**Comment by TechWhiz03** [comment]
I think it's a very weird error

**Comment by TechWhiz03** [comment]
If any of you are ready for a gmeet please help me with this as I'm unable to move forward with this error

**Comment by Divyanshu7031** [comment]
hey TechWhiz...i checked your code on my system actually after saving a copy of yours in my local..& it is actually working fine. here is the proof actually..
![Screenshot 2023-12-25 223039](https://github.com/hiteshchoudhary/chai-backend/assets/153366809/1fdfa651-5769-4d71-b0a4-5d289cda02fe)
so..i can just urge you to restart your system once and have a go again..cause there is literally no error. It is reaaly weird that your are getting a blank somehow.

**Comment by TechWhiz03** [comment]
@Divyanshu7031 ok ill try doing it

**Comment by TechWhiz03** [comment]
@nirajchaurasiya @ganeswar07 @Divyanshu7031 
Thank you for your time and support 👍

**Comment by Divyanshu7031** [comment]
yea..like restart your desktop ..cant see anything other than that

**Comment by Divyanshu7031** [comment]
> @nirajchaurasiya @ganeswar07 @Divyanshu7031 Thank you for your time and support 👍

no problem man..happy to help

**Comment by TechWhiz03** [comment]
Still the error persists can't do any thing with this
