### ISSUE TITLE
env variables are not loading in cloudinary.js

### ISSUE THREAD

**Issue by Rittik003** [hiteshchoudhary/chai-backend#41]
![Screenshot (443)](https://github.com/hiteshchoudhary/chai-backend/assets/90068557/aada8038-1753-48e3-bc38-199155e2997d)

**Comment by kunalrisaanva** [comment]
check the configration of env

**Comment by Rittik003** [comment]
![Screenshot (444)](https://github.com/hiteshchoudhary/chai-backend/assets/90068557/19cf27a1-e434-4717-a279-11a6c4115cd7)
facing issue at the time of loading images into clodinary its showing api key required

**Comment by Munna5553** [comment]
"scripts": {
    "start": "nodemon --env-file=.env src/index.js",
    "dev": "node -r dotenv/config --experimental-json-modules src/index.js"
  },
  use these line. because .env not proper work in moduleJs

**Comment by Rittik003** [comment]
thnx bro now its working properly
