### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by Munna5553** [hiteshchoudhary/chai-backend#42]
const user = await User.create(
        {
            username,
            email,
            fullname,
            avatar: avatar.url,
            coverImage: coverImage?.url || "",
            password,
            refreshToken: ""
        }
    )
    guru ji refresh token database me save nhi ho rha uska field bhi nhi dikha rha h kya usko blank rkh skte h. or i did any mistake

**Comment by kunalrisaanva** [comment]
Bro kal mujhe repo ka link dena or connect ho jana mai bata dunga

**Comment by kunalrisaanva** [comment]
> const user = await User.create(
>         {
>             username,
>             email,
>             fullname,
>             avatar: avatar.url,
>             coverImage: coverImage?.url || "",
>             password,
>             refreshToken: ""
>         }
>     )
>     guru ji refresh token database me save nhi ho rha uska field bhi nhi dikha rha h kya usko blank rkh skte h. or i did any mistake

**Comment by TechWhiz03** [comment]
refresh token login ke time generate hoga,
so when you login thro postman uske baad jake db mein check karo refresh token field aa jayega

**Comment by Munna5553** [comment]
thank everyone but i resolve this myself.. now its proper working, it just a doubt
