### ISSUE TITLE
 Cannot read properties of undefined (reading &#39;0&#39;)

### ISSUE THREAD

**Issue by Abhi-Yadu1C** [hiteshchoudhary/chai-backend#50]
![Screenshot 2024-01-06 170911](https://github.com/hiteshchoudhary/chai-backend/assets/152044989/2a6b478f-8a77-4e93-8ee9-4434d605f37a)

**Comment by 0x-pankaj** [comment]
can i see your code as its working perfectly in mine

**Comment by T0adSage45** [comment]
Bro send the file correctly

**Comment by LovelyBika** [comment]
i am also facing same error mentioned in photo mine was resolved by  replacing below line
**const coverImageLocalPath = req.files?.coverImage[0]?.path;**
by this one 
let coverImageLocalPath;
    if (req.files && Array.isArray(req.files.coverImage) && req.files.coverImage.length > 0) {
        coverImageLocalPath = req.files.coverImage[0].path
    }
but still dont know what is cause for this error and still getting MulterUnexpected Error due to coverImage dont know how can i solve it if someone know plz let me know 
but yes without posting CoverImage to server my rest code is working fine

**Comment by ganeswar07** [comment]
const videoLocalFile = req?.files?.videoFile;
  if (!(videoLocalFile && videoLocalFile[0].path)) {
    throw new ApiError(400, "Video file is required");
  }   try this format

**Comment by abhi-20** [comment]
This is a issue of cloudinary. It is unable to read the .env files. Try writing 
"import * as dotenv from "dotenv";

dotenv.config()

at top of cloudinary.js file

**Comment by snehitshh** [comment]
having the samw issue tried everything you guys said none of them worked :(
someone help pleasee,its getting frustrating now

**Comment by snehitshh** [comment]
will provide the repo too

**Comment by Vishalra-i** [comment]
I think you guys need to check your code once more because my code works wel.

**Comment by snehitshh** [comment]
> I think you guys need to check your code once more because my code works wel.

istg I have been on it for 2 days idk what's the problem

**Comment by Vishalra-i** [comment]
ok ....you can check my repo for solution...https://github.com/Vishalra-i/VideoTube-Youtube-clone/blob/main/src/controller/user.controller.js

**Comment by snehitshh** [comment]
https://github.com/snehitshh/backendStructuring
this is my repo, i cross checked it with you repo(only user.controller) and i find absolutely nothing
it still shows cannot read properties of undefined :(

**Comment by snehitshh** [comment]
also my error is:  Cannot read properties of undefined (reading &#39;0&#39;)

**Comment by Vishalra-i** [comment]
Send me details of your  bugs on my twitter account : https://x.com/Vishal____rai

**Comment by sushil-sagar05** [comment]
Is this bug fixed? i also getting this issue how to fix it any idea?
