### ISSUE TITLE
Cannot POST /api/v1/users/register

### ISSUE THREAD

**Issue by AdityaBVerma** [hiteshchoudhary/chai-backend#80]
![Screenshot 2024-01-19 111140](https://github.com/hiteshchoudhary/chai-backend/assets/148361302/eb8fa224-9008-4ecd-b2a2-f15324815365)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/148361302/5e27fc70-ad23-4b30-beb8-31abc7d262ef)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/148361302/349365a3-9f1d-45c1-9ac5-1bc2f264abae)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/148361302/623cc845-abe9-4272-bd51-546da559a917)
SOMEONE PLEASE POINT OUT WHERE I HAVE GONE WRONG

**Comment by chanderparkash179** [comment]
try to update this below line in controller

```javascript
   return res.status(200).json({ message: "works fine!" });
```

**Comment by SaunakNandi** [comment]
@AdityaBVerma Can I know what are the form-fields you have entered?

**Comment by SaunakNandi** [comment]
@AdityaBVerma can I know why you are not returning the `res` in registerUser ?

**Comment by shahad-hassan19** [comment]
@AdityaBVerma Bhai src/index.js me ye add krke dekhna `import {app} from './app.js'`

 agar ye bhi likha h src/index.js mein, to isko hta dena : `import express from "express"; const app= express();`

Hope it helps!

**Comment by AdityaBVerma** [comment]
@shahad-hassan19 thank you brother this was the actual problem due to my carelessness and sorry for the late reply to everyone as my exams and practicals were going on

**Comment by snehitshh** [comment]
i have the same issue but its not working for me can someone help pleaseee

**Comment by AdityaBVerma** [comment]
@snehitshh can you send the repo link?

**Comment by snehitshh** [comment]
https://github.com/snehitshh/backend_  here you go

**Comment by snehitshh** [comment]
https://github.com/snehitshh/backend_ here you go,but please make sure you have that underscore in the end

**Comment by snehitshh** [comment]
https://github.com/snehitshh/backend_   here you go,but please make sure you have that underscore in the end, i dont know why that underscore is not showing on the link

**Comment by snehitshh** [comment]
https://github.com/snehitshh/backendStructuring   sure here you go

**Comment by AdityaBVerma** [comment]
@snehitshh add the below line in the src/index.js file
import {app} from './app.js'
and remove this from the same file
import express from "express"; 
const app= express();
![image](https://github.com/hiteshchoudhary/chai-backend/assets/148361302/0beb44e7-da0f-4f15-bbef-ebdba9c4cc75)

**Comment by shahad-hassan19** [comment]
@snehitshh Did it work?

**Comment by kavish224** [comment]
I am getting the same issue this is my repo please help
https://github.com/kavish224/Backend

**Comment by shahad-hassan19** [comment]
@kavish224 Index.js and App.js are supposed to be outside of "src" directory, see if this is the problem.

**Comment by kavish224** [comment]
@shahad-hassan19 bro there was a problem in user.model.js I placed a bracket in wrong place now it is fixed thanks for reply

**Comment by bhuvneshsharma007** [comment]
@AdityaBVerma  i am facing the same problem with same code. can you please help me out
below is the repo link:
https://github.com/bhuvneshsharma007/Backend

**Comment by AdityaBVerma** [comment]
@bhuvneshsharma007  can you provide the screenshot of the issue

**Comment by bhuvneshsharma007** [comment]
Postman screenshot
https://github.com/user-attachments/assets/f8d03996-dd80-4e99-8af2-450f35ce0d5f
App.js
https://github.com/user-attachments/assets/eaf53614-1d1d-4082-be0c-02bfbcd5de28
user.router.js
https://github.com/user-attachments/assets/84605676-b596-48c3-95f7-9e582df2a9eb
userController.js
https://github.com/user-attachments/assets/b7a2ff71-3031-4b3f-b56a-93cb306430b3

**Comment by AdityaBVerma** [comment]
in app.js 

app.use("/api/v1.users",userRoutes)

the typo in the route, you have to use v1/users

**Comment by bhuvneshsharma007** [comment]
@AdityaBVerma  Thankyou very very much bro i am stuck here form saturday night.
you have saved my lot of time.
Thanks you bro!!!!

**Comment by imamittiwari** [comment]
![Screenshot 2024-10-12 195251](https://github.com/user-attachments/assets/e4b0ef19-1cd7-430b-8971-21edfc8cea31)



app.js

 https://github.com/i-amit-tiwari/chai-backend/blob/main/src/app.js

index.js: 

https://github.com/i-amit-tiwari/chai-backend/blob/main/src/index.js

controller.js
https://github.com/i-amit-tiwari/chai-backend/blob/main/src/controllers/user.controller.js

route.js

https://github.com/i-amit-tiwari/chai-backend/blob/main/src/routes/user.routes.js


anyone help me resolving this issue

@AdityaBVerma

**Comment by AdityaBVerma** [comment]
the route in postman is wrong 
1. its /users 
and then /register

entire route: {{server}}/api/v1/users/register

**Comment by bhuvneshsharma007** [comment]
Thank you for your response

**Comment by Kuldeep-Rathod** [comment]
Bro I’m facing an issue with creating a new product, whereas creating a new user works perfectly. Can anyone help me identify the problem in my code?
Here’s my repository:  [https://github.com/Kuldeep-Rathod/Ecommerce-Backend.git](https://github.com/Kuldeep-Rathod/Ecommerce-Backend.git)

app.ts
![Screenshot (26)](https://github.com/user-attachments/assets/686a5fb2-5fa7-4eca-a275-ccf3ac1ec475)

product model:
![Screenshot (27)](https://github.com/user-attachments/assets/43484051-9e9a-46e3-a85d-d49e6d15701c)

product controller:
![Screenshot (28)](https://github.com/user-attachments/assets/e4cbab5c-5513-41bf-bb6c-16e89c78732d)

**Comment by SuryaVipul** [comment]
Postman snap
![Image](https://github.com/user-attachments/assets/5243c9dc-51d0-4f2b-b604-a75d44d3acd7)

app.js snap
![Image](https://github.com/user-attachments/assets/36d9ba7f-5d99-44a5-89c7-8a6673fb5dfc)

userRaouter.js snap
![Image](https://github.com/user-attachments/assets/407702d6-8503-4f9a-be59-d107ee34637b)

userController.js snap

![Image](https://github.com/user-attachments/assets/57a3b1f4-6ced-4504-b727-de7e002929c4)

can anyone help me resolving this issue
