### ISSUE TITLE
MongoServerError: Invalid database name:

### ISSUE THREAD

**Issue by SaunakNandi** [hiteshchoudhary/chai-backend#84]
While sending **API** request I getting this error   **Invalid database name: '/VideoApplication'**

This is .env file SC where I am storing the DB_NAME
![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/7cc0503b-e73e-48fa-89b7-1a976b41431d)

inside db/index.js
![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/5eacc4d4-5ed6-45da-9d0d-303a64a8031a)

SC of the error
![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/54ab43d6-a88a-4ff2-8018-ecc5d7a9de84)

But also the user is getting created in **mongodb** and the images are getting uploaded in **cloudinary**.

**Comment by LynxSumit** [comment]
> > may i know the db name in mongoDbCompass or in atlas ? is it `VideoApplication `?

**Comment by uday778** [comment]
can you wrap it in double quotes (DB_NAME="VideoApplication")

**Comment by sagargoel2907** [comment]
Try checking environment variable MONGODB_URL , it should not have / at the end.

**Comment by SaunakNandi** [comment]
@sagargoel2907 noted and updated.
@LynxSumit I created a new project with new URL and that helps>
Thanks guys for helping me out. 
XD

**Comment by Raj-venom** [comment]
> 
MONGODB_URI = yourMongoDbUrl.mongodb.net/ => remove this '/' from the .env file
![image](https://github.com/hiteshchoudhary/chai-backend/assets/91987215/06c73946-6e1b-4982-bb6a-82378f968a55)

your string on db/index.js file is like  :  yourMongoDbUrl.mongodb.net//VideoApplication
![image](https://github.com/hiteshchoudhary/chai-backend/assets/91987215/1584e8a7-7af9-4c50-829d-be1cff4767a6)

and mongoDb is trying to create a database with name '/VideoApplication' so it is throwing error

**Comment by samyakshah3008** [comment]
This is very much helpful, thanks!

**Comment by sumdahl** [comment]
thank you guys,, it got ge mad for 1 hour , i was hitting from postman and seeing all things right but thank you

**Comment by dey-abhirup18** [comment]
> Try checking environment variable MONGODB_URL , it should not have / at the end.

Thanks man
