### ISSUE TITLE
While doing API testing the logout is getting failed and getting Unauthorized request `Need Help`

### ISSUE THREAD

**Issue by SaunakNandi** [hiteshchoudhary/chai-backend#88]
The issue is actually occurring in verifyJWT middleware router.route("/logout").post(verifyJWT, logoutUser);

Inside verifyJWT I console logged the req and what I found is req.cookies is empty. and thereby the token is undefined and I am getting `Unauthorized request` error

Here is the code for verifyJWT 
![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/81e1de4b-e98f-47f8-bec9-d827546e52b5)

An error occurred while attempting to send the request.![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/be5355c0-3c5b-4318-bb64-29e6cc0e5efb)

If you want to check the loginUser here is the response and cookies after doing API testing on {{server}}/users/login.

![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/d0738990-292a-4cfa-badb-8c3e24eebf31)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/63156949/b5c75985-59b5-4cad-8779-c884a77bd867)

This has been done using ThinderClient

**Comment by Rehannn03** [comment]
Is the issue fixed now?

**Comment by kunalrisaanva** [comment]
token not  getting from req.cookies

**Comment by Iliyas-tech** [comment]
Are you passing the token via cookie in thunderclient? Try to do that with postman(There's an option to select cookies)
Follow these steps
Select the Request: Choose the request you want to send to the /logout route.

Go to the Cookies Section: In the request builder interface, you should see tabs for various request components like Headers, Body, Params, etc. Look for the "Cookies" section.

Add a Cookie: Click on the "Cookies" section to expand it. Then, click on the "Add Cookie" button.

Enter the Cookie Name and Value: In the fields that appear, enter the cookie name and value. The cookie name should be accessToken, and the value should be the actual access token you want to pass.

Send the Request: Once you've added the cookie, you can send the request as usual by clicking the "Send" button.

**Let me once if you fix that. Happy to help**

**Comment by SaunakNandi** [comment]
@Iliyas-tech  you are correct. Even doing it with Postman extension doesn't work. It would be best if you had Postman desktop.
Thanks for the instructions buddy.

> Are you passing the token via cookie in thunderclient? Try to do that with postman(There's an option to select cookies) Follow these steps Select the Request: Choose the request you want to send to the /logout route.
> 
> Go to the Cookies Section: In the request builder interface, you should see tabs for various request components like Headers, Body, Params, etc. Look for the "Cookies" section.
> 
> Add a Cookie: Click on the "Cookies" section to expand it. Then, click on the "Add Cookie" button.
> 
> Enter the Cookie Name and Value: In the fields that appear, enter the cookie name and value. The cookie name should be accessToken, and the value should be the actual access token you want to pass.
> 
> Send the Request: Once you've added the cookie, you can send the request as usual by clicking the "Send" button.
> 
> **Let me once if you fix that. Happy to help**

**Comment by SaunakNandi** [comment]
Issue fixed @Rehannn03 @Iliyas-tech

**Comment by It-Is-Ishank** [comment]
I'm still having this issue despite using the Postman desktop.
![image](https://github.com/hiteshchoudhary/chai-backend/assets/102756532/db0734e2-f2a0-46a2-8b81-acb4888eca67)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/102756532/5acd9f33-ac72-4059-a65c-ebe7d73342ce)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/102756532/00443a12-d1cc-4b24-9d0c-4aeee144fa8c)
If you want to check the loginUser here is the response and cookies after doing API testing on {{server}}/users/login.
![image](https://github.com/hiteshchoudhary/chai-backend/assets/102756532/a03f75c8-6a0b-4084-9826-77a90e80f7bf)

![image](https://github.com/hiteshchoudhary/chai-backend/assets/102756532/4de7b115-a0ca-4b17-a0d0-71de3b338100)
