### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by abhi-20** [hiteshchoudhary/chai-backend#94]
Getting this error while logging out user. Please help  !

![image](https://github.com/hiteshchoudhary/chai-backend/assets/58565895/d7b2659e-3171-447f-91df-332092a27956)

**Comment by rajgharat07** [comment]
Can you  share the screenshot of auth.middleware.js and logoutUser controller code?

**Comment by abhi-20** [comment]
![image](https://github.com/hiteshchoudhary/chai-backend/assets/58565895/b860cf69-f1a5-4f07-b889-047e2ed02ccb)
![image](https://github.com/hiteshchoudhary/chai-backend/assets/58565895/6eac4a33-681d-44f7-a6f8-5376b3e750f0)

**Comment by abhi-20** [comment]
The issue has been resolved.
